language: python
cache:
  - pip

python:
  - 2.7

services:
  - postgresql

virtualenv:
  system_site_packages: true


install:
#  - pip install --upgrade setuptools
  - pip install -r requirements.txt

before_script:
  - cd work
  - psql -c 'create database work_app;' -U postgres
#  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput
#  - python manage.py runserver


script:
  - python manage.py check

#  Test
#  - pytest
# py.test
